### ISSUE TITLE
Screen orientation / Speed units

### ISSUE THREAD

**Issue by dougduplessis** [knicholson32/stratux_ahrs#20]
Can't display in portrait mode in chrome browser. Also would like to see NM as ground speed unit

**Comment by knicholson32** [comment]
My apologies for the huge delay in this response.

**Browser Orientation**
Orientation is a tricky topic with this project because it is hard to tell with 100% accuracy what device the user is using and how they want the app oriented. Even using phone accelerometer data, as an example, may be invalid if the phone is mounted to the control column. For this reason, the app will always orient itself in a 'landscape' style. Currently, there is no way to tell the application to force portrait mode. 

_If you are using a desktop_

* One workaround is to resize your browser window to a landscape configuration. 
* Alternately, the chrome developer tools can be used to set the browser viewport to simulate a specific device. More info on that [here](https://developers.google.com/web/tools/chrome-devtools/device-mode#viewport).

If you believe it would be beneficial to have a button on the display to force a portrait mode, please let me know.

**Ground Speed Units**
You can change the ground speed unit to be any unit you prefer by modifying the `configuration.js` file:
```JS
/** ******************************** SPEED ********************************* **/
var speedTape = {
  lowerSpeed: 0,
  upperSpeed: 200,
  speeds: [
    {
      color: COLORS.WHITE,
      start: 55,
      end: 115
    },
    {
      color: COLORS.GREEN,
      start: 64,
      end: 140
    },
    {
      color: COLORS.YELLOW,
      start: 140,
      end: 171
    },
    {
      color: COLORS.RED,
      start: 171,
      end: 200
    }
  ],
  units: UNITS.MPH // <----- Units for displaying speed. 'UNITS.KTS' for knots.
};
/** ******************************** ***** ********************************* **/
```
Available units are as follows:
```JS
UNITS.KTS  // Knots
UNITS.MPH  // Miles per Hour
UNITS.KPH  // Kilometers per Hour
UNITS.FPM  // Feet per Minute
UNITS.FPS  // Feet per Second
UNITS.MPS  // Meters per Second
UNITS.MPM  // Meters per Minute
```

**Comment by dougduplessis** [comment]
Keenan,

A button to force portrait would be very useful. "I" have never seen anyone flying with a tablet on their yoke in landscape mode. Thank you!

Doug

Doug Du Plessis

________________________________

**Comment by knicholson32** [comment]
Great example, I'll re-open this and start looking into it. Thanks for the suggestion!

**Comment by knicholson32** [comment]
Just finished adding a button in the menu ("Toggle Rotation" - have to scroll to see it) that forces the screen to rotate orientations. It is still recommended to lock screen orientation on your device, but in that locked state you should now be able to set portrait or landscape. Let me know how it works for you - it seems to work well in Chrome and on my iPhone, but not all devices act the same in these regards.

**Comment by DocTopi** [comment]
Hi Keenan, in landscape mode the readability is very good. But in my opinion the further development should prefer the portrait mode - Doug is right.
In portrait mode the readability should be improved, and furthermore portrait mode offers the possibility for splitting the screen like Aspen Avionics E5: AHRS in the upper section, compass arc in the lower section. The compass arc should be selectable orientated in geographic = true north and magnetic north and should have a bug for selectable input the GPS-desired track or magnetic heading referring to this. Next a HSI screen with lateral course deviation could computed  ... and with your code the iPhone is a very great instrument for checking the certified installed avionics.
I don´t know, if the iPhone´s magnetic sensors are suitable. Or would it be more suitable upgrading the stratux project with a magnetic sensor?
Please open isssues according to my suggestions. 
Thanks and kind regards 
Franz
